namespace: portfolio

replicaCount: 1

image:
  repository: ghcr.io/tomdein/portfolio  # Replace tomdein with your GitHub username
  tag: "" # The tag will be set by the release workflow, so it can be left empty here
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

publicContent:
  hostPath: /data/portfolio/public  # Path on the cluster node to mount as /usr/share/nginx/html

ingress:
  host: tomdein.deini.eu  # Replace with your domain
  className: traefik # Set to your ingress class if needed, e.g., "nginx" or "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: tomdein.deini.eu
    cert-manager.io/cluster-issuer: letsencrypt
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
    enabled: true
    secretName: portfolio-tls-secret
